// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dyad_ratios_cpp
List dyad_ratios_cpp(NumericMatrix data_matrix, int nperiods, int nVar, int npass, bool smoothing, double tola_in, int beginper, int endper, NumericVector raw_av, NumericVector raw_std, int seed);
RcppExport SEXP _DyadRatios_dyad_ratios_cpp(SEXP data_matrixSEXP, SEXP nperiodsSEXP, SEXP nVarSEXP, SEXP npassSEXP, SEXP smoothingSEXP, SEXP tola_inSEXP, SEXP beginperSEXP, SEXP endperSEXP, SEXP raw_avSEXP, SEXP raw_stdSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_matrix(data_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type nperiods(nperiodsSEXP);
    Rcpp::traits::input_parameter< int >::type nVar(nVarSEXP);
    Rcpp::traits::input_parameter< int >::type npass(npassSEXP);
    Rcpp::traits::input_parameter< bool >::type smoothing(smoothingSEXP);
    Rcpp::traits::input_parameter< double >::type tola_in(tola_inSEXP);
    Rcpp::traits::input_parameter< int >::type beginper(beginperSEXP);
    Rcpp::traits::input_parameter< int >::type endper(endperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type raw_av(raw_avSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type raw_std(raw_stdSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(dyad_ratios_cpp(data_matrix, nperiods, nVar, npass, smoothing, tola_in, beginper, endper, raw_av, raw_std, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DyadRatios_dyad_ratios_cpp", (DL_FUNC) &_DyadRatios_dyad_ratios_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_DyadRatios(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
